"""
    parse_cli(::Type{T}, args::Vector{String}=ARGS;
              allow_empty_option_value::Bool=false,
              help::HelpTemplateOptions=HelpTemplateOptions()) where {T}

Parse command-line arguments into an instance of a type generated by
[`@CMD_MAIN`](@ref).

`parse_cli` is the primary high-level parsing entry point for RunicCLI. It
accepts a generated CLI type and a vector of command-line tokens, invokes the
parser constructor created by [`@CMD_MAIN`](@ref), and returns a fully typed
result object of type `T`.

It also resolves help rendering behavior through [`HelpTemplateOptions`](@ref).
If parsing raises [`ArgHelpRequested`](@ref), `parse_cli` renders the help text
using the resolved template and rethrows the exception with its `message` field
pre-populated.

# Parameters

- `T`  
  A concrete type generated by [`@CMD_MAIN`](@ref).

- `args::Vector{String}=ARGS`  
  Argument token vector to parse.

- `allow_empty_option_value::Bool=false`  
  Controls whether empty option values are accepted in parsing paths that
  support that behavior.

- `help::HelpTemplateOptions=HelpTemplateOptions()`  
  Help-template configuration used when a help request is triggered.

For all help-related configuration fields, see [`HelpTemplateOptions`](@ref).

# Return value

Returns an instance of `T` populated according to the declared CLI schema.

# Error behavior

- Throws `ArgumentError` if `T` is not a generated main CLI type.
- Throws [`ArgParseError`](@ref) on invalid command-line input.
- Throws [`ArgHelpRequested`](@ref) on help requests.

# Example

```julia
opts = parse_cli(MyCLI, ["--port", "9000", "input.txt"])
```

With custom help rendering:

```julia
opts = parse_cli(
    MyCLI, ARGS;
    help = HelpTemplateOptions(style=HELP_COLORED)
)
```

# See also

[`@CMD_MAIN`](@ref), [`run_cli`](@ref), [`render_help`](@ref),
[`build_help_template`](@ref), [`HelpTemplateOptions`](@ref)
"""
function parse_cli(
    ::Type{T},
    args::Vector{String}=ARGS;
    allow_empty_option_value::Bool=false,
    help::HelpTemplateOptions=HelpTemplateOptions(),
    env::AbstractDict=ENV,
    config::AbstractDict=Dict{String,Any}(),
    config_file::Union{Nothing,String}=nothing
) where {T}
    if !(hasfield(T, :subcommand) && hasfield(T, :subcommand_args))
        throw(ArgumentError("parse_cli expects a @CMD_MAIN generated type"))
    end

    local resolved_template = build_help_template(help)

    try
        return T(
            args;
            allow_empty_option_value=allow_empty_option_value,
            env=env,
            config=config,
            config_file=config_file
        )
    catch e
        if e isa ArgHelpRequested
            throw(ArgHelpRequested(e.def, e.path, isempty(e.message) ? render_help(e.def; template=resolved_template, path=e.path) : e.message))
        else
            rethrow()
        end
    end
end



"""
    run_cli(f::Function; io::IO=stdout, err_io::IO=stderr, debug::Bool=false,
            on_error::Function=(e)->nothing, help::HelpTemplateOptions=HelpTemplateOptions()) -> Int

Execute a CLI entry function with standardized handling for help requests and
argument parsing failures.

`run_cli` is a convenience wrapper intended for application entrypoints. It runs
the provided function `f`, captures RunicCLI-specific exceptions, prints help or
error output to the appropriate streams, and returns a process-style exit code.

# Behavior

- If `f()` succeeds, returns `0`.
- If `f()` throws [`ArgHelpRequested`](@ref), help text is printed to `io` and
  `0` is returned.
- If `f()` throws [`ArgParseError`](@ref), the error is printed to `err_io` and
  `2` is returned.
- Any other exception is rethrown after `on_error(e)` is called.

# Parameters

## Execution and output

- `f::Function`  
  Application entry function to execute.

- `io::IO=stdout`  
  Stream used for help output.

- `err_io::IO=stderr`  
  Stream used for parse errors and optional debug backtraces.

- `debug::Bool=false`  
  If `true`, `ArgParseError` handling also prints a backtrace.

- `on_error::Function=(e)->nothing`  
  Callback invoked for `ArgParseError` and unexpected exceptions.

## Help configuration

- `help::HelpTemplateOptions=HelpTemplateOptions()`  
  Help-template configuration used when rendering help for caught
  [`ArgHelpRequested`](@ref) exceptions.

For all help-template fields and customization behavior, see
[`HelpTemplateOptions`](@ref).

# Return codes

- `0` for success or explicit help requests
- `2` for argument parsing failures

Unexpected exceptions are not converted into exit codes.

# Example

```julia
code = run_cli() do
    opts = parse_cli(MyCLI)
    # application logic
end
```

With custom help configuration:

```julia
code = run_cli(help=HelpTemplateOptions(style=HELP_COLORED)) do
    parse_cli(MyCLI)
end
```

# See also

[`parse_cli`](@ref), [`render_help`](@ref), [`build_help_template`](@ref),
[`HelpTemplateOptions`](@ref), [`ArgParseError`](@ref),
[`ArgHelpRequested`](@ref)
"""
function run_cli(
    f::Function;
    io::IO=stdout,
    err_io::IO=stderr,
    debug::Bool=false,
    on_error::Function = (e)->nothing,
    help::HelpTemplateOptions=HelpTemplateOptions()
)::Int
    local resolved_template = build_help_template(help)

    try
        f()
        return 0
    catch e
        if e isa ArgHelpRequested
            local msg = if !isempty(e.message)
                e.message
            else
                render_help(e.def; template=resolved_template, path=e.path)
            end
            if !isempty(msg)
                print(io, msg)
                endswith(msg, '\n') || println(io)
            end
            return 0
        elseif e isa ArgParseError
            println(err_io, sprint(showerror, e))
            on_error(e)
            if debug
                println(err_io, "---- debug backtrace ----")
                Base.showerror(err_io, e, catch_backtrace())
                println(err_io)
                println(err_io, "-------------------------")
            end
            return 2
        else
            on_error(e)
            rethrow()
        end
    end
end
